export const MESSAGE = {
  // lobby
  CONNECT_LOBBY: "connect_lobby",
  CLIENT_IDENTIFIED: "client_identified",
  CREATE_ROOM: "create_room",
  UPDATE_ROOM: "update_room",
  LIST_ROOMS: "list_rooms",
  ROOM_LIST: "room_list",
  ROOM_DETAIL: "room_detail",
  JOIN_ROOM: "join_room",
  LEAVE_ROOM: "leave_room",
  SET_READY: "set_ready",
  JOINED_ROOM: "joined_room",
  ROOM_CLOSED: "room_closed",
  ROOM_CHAT: "room_chat",
  START_MATCH: "start_match",
  MATCH_STARTING: "match_starting",
  UPDATE_MY_SLOT: "update_my_slot",

  // gameplay
  JOIN: "join",
  LEAVE: "leave",
  WELCOME: "welcome",
  INPUT: "input",
  SNAPSHOT: "snapshot",
  ERROR: "error",
  PLAYER_FIRED: "player_fired",
  ROUND_START: "round_start",
  PICKUP_POWER_UP: "pickup_power_up",
  GAMEPLAY_CHAT: "gameplay_chat",
};
